Repository GSG-CF05/Planet-Guide, pull requests merged in 2022-03, with the labels that each got.

#2 create file structure relates #1
  aboutUs/aboutUs.css
  aboutUs/aboutUs.html
  aboutUs/aboutUs.js
  homePage/homePage.css
  homePage/homePage.html
  homePage/homePage.js
  index.html
  planetPage/planetPage.css
  planetPage/planetPage.html
  planetPage/planetPage.js
  style.css
Labels: done

#4 add assest file
  assest/Desktop Background landing 1.png
  assest/Desktop Home & info background.png
  assest/Earth.png
  assest/Home & info background.png
  assest/Jupiter.png
  assest/Landing mobile background.png
  assest/Mars.png
  assest/Mercury.png
  assest/Neptune.png
  assest/Saturn.png
  assest/Uranus.png
  assest/Venus.png
  assest/about backround.png
Labels: approved

#8 edit the file name from assest to assets
  assets/Desktop Background landing 1.png
  assets/Desktop Home & info background.png
  assets/Earth.png
  assets/Home & info background.png
  assets/Jupiter.png
  assets/Landing mobile background.png
  assets/Mars.png
  assets/Mercury.png
  assets/Neptune.png
  assets/Saturn.png
  assets/Uranus.png
  assets/Venus.png
  assets/about backround.png
  assets/black right arrow.png
  assets/left arrow.png
  assets/red right arrow.png
  assets/slider arrow1.png
  assets/slider arrow2.png
Labels: approved

#9 I create the structure of the html file of the home page relates #5
  homePage/homePage.html
Labels: awaiting-review

#10 I create homePage.css file relates #5
  homePage/homePage.css
Labels: awaiting-review

#11 6 create landingpage html css
  index.html
  style.css
Labels: approved

#12 i update the font size and font family of the body relates#5
  homePage/homePage.css
Labels: awaiting-review

#15 14 add responsive home page
  assest/Desktop Background landing 1.png
  assest/Earth.png
  assest/Jupiter.png
  assest/Landing mobile background.png
  assest/Mars.png
  assest/Mercury.png
  assest/Neptune.png
  assest/Saturn.png
  assest/Uranus.png
  assest/Venus.png
  assest/about backround.png
  homePage/Desktop Home & info background.png
  homePage/Home & info background.png
  homePage/homePage.css
Labels: approved

#18 Create home page to planet page link. Relates #17
  homePage/homePage.css
  homePage/homePage.html
  homePage/homePage.js
  index.html
Labels: awaiting-review

#20 Edit img url
  homePage/Desktop Home & info background.png
  homePage/Home & info background.png
  homePage/homePage.css
Labels: approved

#27 fetching the planet info > relates #26
  planetPage/planetPage.js
Labels: awaiting-review

#31 Building the html of the info portion
  planetPage/planetPage.js
Labels: awaiting-review

#33 Create README
  README.md
Labels: awaiting-review

#37 fetching another api that get related artical of evry plant
  planetPage/planetPage.js
Labels: awaiting-review

#41 35 create slider
  aboutUs/aboutUs.css
  aboutUs/aboutUs.html
  aboutUs/aboutUs.js
  assets/aref.jpeg
  assets/avatar 1.jpeg
  assets/avatar 2.jpeg
  assets/avatar 3.jpeg
  assets/avatar 4.jpeg
Labels: awaiting-review

#42 Edit the wrong in (JS)Bulding html for Planet page
  planetPage/planetPage.js
Labels: awaiting-review

#44 edit button link
  index.html
Labels: awaiting-review

#46 Edit Path on all pages to resolve GitHub pages problem
  aboutUs/aboutUs.html
  homePage/homePage.css
  homePage/homePage.html
  index.html
  planetPage/planetPage.css
  planetPage/planetPage.html
  style.css
Labels: awaiting-review

#50 Building the html of the article portion
  planetPage/planetPage.js
Labels: approved

#49 Edit background path
  aboutUs/aboutUs.css
Labels: awaiting-review
